name = "oioio"
main = "_worker.js"
compatibility_date = "2025-11-22"
compatibility_flags = ["nodejs_compat"]

[vars]
# URL302 = ""
# URL = "nginx"
# UA = ""
# Docker Hub 认证信息（请通过 Cloudflare Workers 环境变量设置）
# DOCKER_USERNAME = "your_dockerhub_username"
# DOCKER_PASSWORD = "your_dockerhub_token"

[[kv_namespaces]]
binding = "DOCKER_AUTH"
id = "448e71cd666a4b78ba6dcc5213fbf48d"
#preview_id = "your_preview_kv_namespace_id"